# create build for local docker file

services:
  agent:
    build: .

    volumes:
      - ./data:/data
      - ./logs:/logs

    ports:
      - "8001:8001"

  qdrant:
    image: qdrant/qdrant:latest
    
    ports:
      - "6333:6333"