# create build for local docker file

services:
  agent:
    build: .

    volumes:
      - ./data:/data
      - ./logs:/logs

    ports:
      - "8001:8001"

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - "./qdrant_storage:/qdrant/storage"
      - "./config/qdrant.yaml:/qdrant/config/production.yaml"
    ports:
      - "6333:6333"
