[tool.poetry]
name = "agent"
version = "3.0.0"
description = ""
authors = ["Marc Mezger <marc.mezger@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
langchain = "^0.2.12"
loguru = "^0.7.2"
omegaconf = "^2.3.0"
aleph-alpha-client = "^7.1.0"
tiktoken = "^0.7.0"
python-dotenv = "^1.0.1"
httpx = "^0.27.0"
python-multipart = "^0.0.9"
fastapi = "^0.112.0"
openai = "^1.35.3"
qdrant-client = "^1.8.2" # for qdrant
uvicorn = "^0.30.1"
gpt4all = "^2.7.0"
nltk = "^3.8.1"
pypdfium2 = "^4.30.0"
lingua-language-detector = "^2.0.2"
pyarrow = "^16.1.0" # security issue with < 14.0.1
aiohttp = "^3.9.5" # security issue
ultra-simple-config = "^0.1.0"
gitpython = "^3.1.43" # https://github.com/advisories/GHSA-wfm5-v35h-vwf4
jinja2 = "^3.1.4"
langchain-openai = "^0.1.9"
langchain-cohere = "^0.1.5"
langchain-community = "^0.2.4"
langchain-qdrant = "^0.1.0"
langgraph = "^0.1.1"
arize-phoenix = {extras = ["evals"], version = "^4.5.0"}
werkzeug = "^3.0.3"


[tool.poetry.group.dev.dependencies]
mypy = "^1.11.0"
ruff = "^0.5.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.settings]
known_third_party = ["aleph_alpha_client", "dotenv", "fastapi", "gpt4all", "gpt4all_service", "httpx", "langchain", "langchain_community", "langchain_core", "lingua", "loguru", "nltk", "numpy", "omegaconf", "openai", "pydantic", "pytest", "qdrant_client", "requests", "starlette", "streamlit", "tqdm", "ultra_simple_config"]

[tool.mypy]
# Disallow dynamic typing
disallow_any_unimported=true
disallow_any_expr = true
disallow_any_decorated = true
disallow_any_generics = true
disallow_any_explicit = true
disallow_subclassing_any = true

# Disallow untyped definitions and calls
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true

# None and optional handling
no_implicit_optional = true

# Configuring warnings
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_redundant_casts = true

# Misc things
strict_equality = true

# Config file
warn_unused_configs = true
