[tool.poetry]
name = "agent"
version = "0.1.0"
description = ""
authors = ["Marc Mezger <marc.mezger@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.10"
langchain = "^0.0.129"
streamlit = "^1.20.0"
loguru = "^0.6.0"
omegaconf = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
