name: pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org/ | POETRY_HOME=/opt/poetry python
        cd /usr/local/bin && ln -s /opt/poetry/bin/poetry
        poetry config virtualenvs.create false
        poetry install --no-root
    - name: Run tests
      run: pytest tests/
